/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _AboutRoute } from '../pages/about';
import { Route as _AiTodayOneCardRoute } from '../pages/ai-today-one-card';
import { Route as _ChatbotRoute } from '../pages/chatbot';
import { Route as _CompatibilityRoute } from '../pages/compatibility';
import { Route as _ContentsWorkRoute } from '../pages/contents/work';
import { Route as _ContentsRoute } from '../pages/contents';
import { Route as _HomeRoute } from '../pages/home';
import { Route as _IndexRoute } from '../pages/';
import { Route as _PrivacyRoute } from '../pages/privacy';
import { Route as _SettingsRoute } from '../pages/settings';
import { Route as _TarotCompatibilityRoute } from '../pages/tarot/compatibility';
import { Route as _TarotHoroscopeRoute } from '../pages/tarot/horoscope';
import { Route as _TarotLoveRoute } from '../pages/tarot/love';
import { Route as _TarotMoneyRoute } from '../pages/tarot/money';
import { Route as _TarotMonthlyRoute } from '../pages/tarot/monthly';
import { Route as _TarotNewYearRoute } from '../pages/tarot/new-year';
import { Route as _TarotPalmRoute } from '../pages/tarot/palm';
import { Route as _TarotReunionRoute } from '../pages/tarot/reunion';
import { Route as _TarotStudentRoute } from '../pages/tarot/student';
import { Route as _TarotWeeklyRoute } from '../pages/tarot/weekly';
import { Route as _TarotWorkRoute } from '../pages/tarot/work';
import { Route as _TarotYearlyRoute } from '../pages/tarot/yearly';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/about': (typeof _AboutRoute)['_inputType'];
    '/ai-today-one-card': (typeof _AiTodayOneCardRoute)['_inputType'];
    '/chatbot': (typeof _ChatbotRoute)['_inputType'];
    '/compatibility': (typeof _CompatibilityRoute)['_inputType'];
    '/contents/work': (typeof _ContentsWorkRoute)['_inputType'];
    '/contents': (typeof _ContentsRoute)['_inputType'];
    '/home': (typeof _HomeRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
    '/privacy': (typeof _PrivacyRoute)['_inputType'];
    '/settings': (typeof _SettingsRoute)['_inputType'];
    '/tarot/compatibility': (typeof _TarotCompatibilityRoute)['_inputType'];
    '/tarot/horoscope': (typeof _TarotHoroscopeRoute)['_inputType'];
    '/tarot/love': (typeof _TarotLoveRoute)['_inputType'];
    '/tarot/money': (typeof _TarotMoneyRoute)['_inputType'];
    '/tarot/monthly': (typeof _TarotMonthlyRoute)['_inputType'];
    '/tarot/new-year': (typeof _TarotNewYearRoute)['_inputType'];
    '/tarot/palm': (typeof _TarotPalmRoute)['_inputType'];
    '/tarot/reunion': (typeof _TarotReunionRoute)['_inputType'];
    '/tarot/student': (typeof _TarotStudentRoute)['_inputType'];
    '/tarot/weekly': (typeof _TarotWeeklyRoute)['_inputType'];
    '/tarot/work': (typeof _TarotWorkRoute)['_inputType'];
    '/tarot/yearly': (typeof _TarotYearlyRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/about': (typeof _AboutRoute)['_outputType'];
    '/ai-today-one-card': (typeof _AiTodayOneCardRoute)['_outputType'];
    '/chatbot': (typeof _ChatbotRoute)['_outputType'];
    '/compatibility': (typeof _CompatibilityRoute)['_outputType'];
    '/contents/work': (typeof _ContentsWorkRoute)['_outputType'];
    '/contents': (typeof _ContentsRoute)['_outputType'];
    '/home': (typeof _HomeRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
    '/privacy': (typeof _PrivacyRoute)['_outputType'];
    '/settings': (typeof _SettingsRoute)['_outputType'];
    '/tarot/compatibility': (typeof _TarotCompatibilityRoute)['_outputType'];
    '/tarot/horoscope': (typeof _TarotHoroscopeRoute)['_outputType'];
    '/tarot/love': (typeof _TarotLoveRoute)['_outputType'];
    '/tarot/money': (typeof _TarotMoneyRoute)['_outputType'];
    '/tarot/monthly': (typeof _TarotMonthlyRoute)['_outputType'];
    '/tarot/new-year': (typeof _TarotNewYearRoute)['_outputType'];
    '/tarot/palm': (typeof _TarotPalmRoute)['_outputType'];
    '/tarot/reunion': (typeof _TarotReunionRoute)['_outputType'];
    '/tarot/student': (typeof _TarotStudentRoute)['_outputType'];
    '/tarot/weekly': (typeof _TarotWeeklyRoute)['_outputType'];
    '/tarot/work': (typeof _TarotWorkRoute)['_outputType'];
    '/tarot/yearly': (typeof _TarotYearlyRoute)['_outputType'];
  }
}
