/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _AboutRoute } from '../pages/about';
import { Route as _AiTodayOneCardRoute } from '../pages/ai-today-one-card';
import { Route as _ChatbotRoute } from '../pages/chatbot';
import { Route as _ContentsWorkRoute } from '../pages/contents/work';
import { Route as _ContentsRoute } from '../pages/contents';
import { Route as _HomeRoute } from '../pages/home';
import { Route as _IndexRoute } from '../pages/';
import { Route as _LoungeRoute } from '../pages/lounge';
import { Route as _PrivacyRoute } from '../pages/privacy';
import { Route as _SettingsRoute } from '../pages/settings';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/about': (typeof _AboutRoute)['_inputType'];
    '/ai-today-one-card': (typeof _AiTodayOneCardRoute)['_inputType'];
    '/chatbot': (typeof _ChatbotRoute)['_inputType'];
    '/contents/work': (typeof _ContentsWorkRoute)['_inputType'];
    '/contents': (typeof _ContentsRoute)['_inputType'];
    '/home': (typeof _HomeRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
    '/lounge': (typeof _LoungeRoute)['_inputType'];
    '/privacy': (typeof _PrivacyRoute)['_inputType'];
    '/settings': (typeof _SettingsRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/about': (typeof _AboutRoute)['_outputType'];
    '/ai-today-one-card': (typeof _AiTodayOneCardRoute)['_outputType'];
    '/chatbot': (typeof _ChatbotRoute)['_outputType'];
    '/contents/work': (typeof _ContentsWorkRoute)['_outputType'];
    '/contents': (typeof _ContentsRoute)['_outputType'];
    '/home': (typeof _HomeRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
    '/lounge': (typeof _LoungeRoute)['_outputType'];
    '/privacy': (typeof _PrivacyRoute)['_outputType'];
    '/settings': (typeof _SettingsRoute)['_outputType'];
  }
}
